"""
Phase configuration registry.
Maps each phase number to its Environment constructor kwargs
and UI metadata (name, description, feature flags).
"""

PHASE_CONFIGS = {
    1: {
        "name": "MVP — Single Warehouse",
        "description": "A single Central Warehouse supplies one Regional Warehouse. "
                       "The agent decides each day: ship or don't ship.",
        "folder": "1_mvp",
        "features": {
            "manufacturer": False,
            "variable_sizing": False,
            "stochastic": False,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 1,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": 2,
            "lead_time": 3,
            "sim_length": 100,
        },
    },
    2: {
        "name": "Multiple Regional Warehouses",
        "description": "Scales to 3 independent Regional Warehouses, each with its own "
                       "customer demand. The agent manages shipments to all of them.",
        "folder": "2_multiple_rw",
        "features": {
            "manufacturer": False,
            "variable_sizing": False,
            "stochastic": False,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 200,
            "demand": [2, 1, 3],
            "lead_time": 2,
            "shipment_amount": 10,
            "sim_length": 100,
        },
    },
    3: {
        "name": "Production Plant",
        "description": "Adds an upstream Manufacturer that produces goods and ships them "
                       "to the Central Warehouse. The CW now depletes its inventory on shipments.",
        "folder": "3_production_plant",
        "features": {
            "manufacturer": True,
            "variable_sizing": False,
            "stochastic": False,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": [2, 1, 3],
            "lead_time": 2,
            "shipment_amount": 10,
            "cw_shipment_amount": 15,
            "mf_prod_capacity": 10,
            "manufacturer": True,
            "sim_length": 100,
        },
    },
    4: {
        "name": "Variable Ordering Sizes",
        "description": "The agent can now choose from multiple shipment sizes (5 or 10 units). "
                       "Introduces shipping costs and inventory holding cost rewards.",
        "folder": "4_variable_ordering_size",
        "features": {
            "manufacturer": True,
            "variable_sizing": True,
            "stochastic": False,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": [2, 1, 3],
            "lead_time": 2,
            "shipment_amount": [5, 10],
            "cw_shipment_amount": 15,
            "manufacturer": True,
            "mf_prod_capacity": 10,
            "shipment_var_cost_per_unit": 0.01,
            "shipment_fixed_cost": 0.05,
            "inventory_holding_cost_multiplier": 1,
            "sim_length": 100,
        },
    },
    5: {
        "name": "Stochastic Parameters & Prioritisation",
        "description": "Customer demand and lead times now fluctuate randomly. "
                       "Customers get priority levels that weight the lost-sales penalty.",
        "folder": "5_stochastic_params_and_priorisation",
        "features": {
            "manufacturer": True,
            "variable_sizing": True,
            "stochastic": True,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": [3, 2, 4],
            "lead_time": 3,
            "shipment_amount": [5, 10],
            "cw_shipment_amount": 15,
            "manufacturer": True,
            "mf_prod_capacity": 10,
            "shipment_var_cost_per_unit": 0.01,
            "shipment_fixed_cost": 0.05,
            "inventory_holding_cost_multiplier": 1,
            "demand_fluctuation": 2,
            "lead_time_fluctuation": 1,
            "cw_inventory_holding_cost_multiplier": 0.5,
            "customer_priorities": [1, 2, 3],
            "sim_length": 100,
        },
    },
    6: {
        "name": "Advanced Observation Space",
        "description": "Same network as Phase 5, but the RL agent now observes richer "
                       "state representations (shipment arrivals, in-transit amounts).",
        "folder": "6_observation_space_testing",
        "features": {
            "manufacturer": True,
            "variable_sizing": True,
            "stochastic": True,
            "forecasting": False,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": [3, 2, 4],
            "lead_time": 3,
            "shipment_amount": [5, 10],
            "cw_shipment_amount": 15,
            "manufacturer": True,
            "mf_prod_capacity": 10,
            "shipment_var_cost_per_unit": 0.01,
            "shipment_fixed_cost": 0.05,
            "inventory_holding_cost_multiplier": 1,
            "demand_fluctuation": 2,
            "lead_time_fluctuation": 1,
            "cw_inventory_holding_cost_multiplier": 0.5,
            "customer_priorities": [1, 2, 3],
            "sim_length": 100,
        },
    },
    7: {
        "name": "Demand Forecasting",
        "description": "Integrates a predictive demand simulation. The agent receives "
                       "forecasted demand curves and must plan shipments proactively.",
        "folder": "7_demand_forecasting",
        "features": {
            "manufacturer": True,
            "variable_sizing": True,
            "stochastic": True,
            "forecasting": True,
        },
        "env_kwargs": {
            "number_of_regional_wh": 3,
            "rw_inventory_limit": 49,
            "cw_inventory_limit": 100,
            "demand": [3, 2, 4],
            "lead_time": 3,
            "shipment_amount": [5, 10],
            "manufacturer": True,
            "shipment_var_cost_per_unit": 0.01,
            "shipment_fixed_cost": 0.05,
            "demand_fluctuation": 2,
            "lead_time_fluctuation": 1,
            "customer_priorities": [1, 2, 3],
            "cw_shipment_amount": 20,
            "mf_prod_capacity": 15,
            "inventory_holding_cost_multiplier": 1,
            "cw_inventory_holding_cost_multiplier": 0.5,
            "rw_inventory_holding_cost_drop_off": 1,
            "cw_inventory_holding_cost_drop_off": 0.25,
            "manufacturer_inventory_limit": 200,
            "forecast_range": 10,
            "forecast_deviation_factor": 1,
            "use_advanced_demand_simulation": True,
            "demand_curve_length_multiplier": 1,
            "new_demand_curve_on_reset": True,
            "sim_length": 100,
        },
    },
}
